In [1]:
#import pandas as pd
import xarray as xr

In [3]:
ds = xr.open_dataset('_grib2netcdf-atls00-95e2cf679cd58ee9b4db4dd119a05a8d-UIcz7w.nc')

In [5]:
ds.to_dataframe()

                                              u10
latitude longitude time
 90.0    0.00      2015-12-01 18:00:00  -3.790418
                   2015-12-02 18:00:00  -7.474918
                   2015-12-03 18:00:00 -13.199034
                   2015-12-04 18:00:00  -9.979039
                   2015-12-05 18:00:00  -6.977916
                   2015-12-06 18:00:00  -4.258746
                   2015-12-07 18:00:00  -2.467630
                   2015-12-08 18:00:00  -5.378911
                   2015-12-09 18:00:00  -5.665642
                   2015-12-10 18:00:00  -4.545478
                   2015-12-11 18:00:00  -3.779905
                   2015-12-12 18:00:00  -7.000855
                   2015-12-13 18:00:00  -7.577185
                   2015-12-14 18:00:00  -0.203407
                   2015-12-15 18:00:00   2.985047
                   2015-12-16 18:00:00   4.057423
                   2015-12-17 18:00:00   3.378825
                   2015-12-18 18:00:00  -0.067688
                   2015-12-19 18:00:00   3.116944
                   2015-12-20 18:00:00  -1.330262
                   2015-12-21 18:00:00  -1.965850
                   2015-12-22 18:00:00  -2.118774
                   2015-12-23 18:00:00  -0.422279
                   2015-12-24 18:00:00   2.313140
                   2015-12-25 18:00:00   3.057686
                   2015-12-26 18:00:00   1.546611
                   2015-12-27 18:00:00  12.069656
                   2015-12-28 18:00:00   4.425395
                   2015-12-29 18:00:00 -11.545549
                   2015-12-30 18:00:00   8.783714
...                                           ...
-90.0    359.25    2015-12-02 18:00:00  -1.822484
                   2015-12-03 18:00:00  -4.759571
                   2015-12-04 18:00:00  -2.665475
                   2015-12-05 18:00:00   2.077064
                   2015-12-06 18:00:00   2.305493
                   2015-12-07 18:00:00   6.793797
                   2015-12-08 18:00:00  -0.343906
                   2015-12-09 18:00:00  -5.122764
                   2015-12-10 18:00:00  -8.108594
                   2015-12-11 18:00:00  -8.721244
                   2015-12-12 18:00:00  -4.841767
                   2015-12-13 18:00:00  -5.044390
                   2015-12-14 18:00:00  -0.455731
                   2015-12-15 18:00:00  -0.965157
                   2015-12-16 18:00:00   0.785816
                   2015-12-17 18:00:00   3.516456
                   2015-12-18 18:00:00  -1.530974
                   2015-12-19 18:00:00  -1.094186
                   2015-12-20 18:00:00   0.369100
                   2015-12-21 18:00:00   0.900509
                   2015-12-22 18:00:00   1.098354
                   2015-12-23 18:00:00  -3.283859
                   2015-12-24 18:00:00  -6.562156
                   2015-12-25 18:00:00  -1.739332
                   2015-12-26 18:00:00  -1.704924
                   2015-12-27 18:00:00  -3.732116
                   2015-12-28 18:00:00  -2.195235
                   2015-12-29 18:00:00  -0.284648
                   2015-12-30 18:00:00  -4.037007
                   2015-12-31 18:00:00  -4.598045

[3586080 rows x 1 columns]